import { createElement } from '@lwc/engine-dom';
import Rg9_CountdownTimer from 'c/rg9_CountdownTimer';

describe('c-rg9-countdown-timer', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-rg9-countdown-timer', {
            is: Rg9_CountdownTimer
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});